# Check `.github/actions/find-libraries/dist/index.js` to ensure it was built
# before pushing the latest commit - we check in the built javascript file,
# and we need to ensure there are no further changes beyond what was built.

name: Check action dist

on:
  pull_request:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: cd .github/actions/find-libraries && npm ci

      - name: Rebuild the dist/ directory
        run: |
          cd .github/actions/find-libraries
          npm run build
          npm run package

      - name: Compare the expected and actual dist/ directories
        run: |
          cd .github/actions/find-libraries
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
