name: update-index

on:
  workflow_dispatch: {}  # allow manual trigger
  schedule:
    - cron: "0 10 * * *" # daily at 10:00 UTC
  push:
    branches: [main]     # on main branch commits

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/find-libraries
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: Commit changes
        run: |
          git config user.email savi-lang-bot@gmail.com
          git config user.name savi-lang-bot

          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only

          git add .

          git commit -m "Update library index" || echo "Nothing to commit."
          git push github HEAD:${GITHUB_REF}
